export const SET_REPO_NAME = 'SET_REPO_NAME';
export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_REQUEST_ERROR = 'SET_REQUEST_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
